# Rebuild the docs on changes to dev or on a new release

name: Update the dev version of the docs

on:
  push:
    branches:
    - dev
    - release
jobs:
  docs_rebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: set up development environment
      run: |
        $CONDA/bin/conda env create -q -f environment.yml
        pip install -e .
    - name: configure git
      run: |
        git config --global user.name docs-golem
        git config --global user.email losthemobvote@openbagtwo.net
    - name: deploy current branch
      run: |
        source $CONDA/bin/activate enderchest
        mike deploy ${{ GITHUB_REF_NAME }} --push --rebase
